### ISSUE TITLE
`jx admin create` contains helper text which refers to jx remote

### ISSUE THREAD

**Issue by rawlingsj** [jenkins-x/jx-admin#2]
After running `jx admin create` we see some helper text for next steps:
```
git clone https://github.com/cb-kubecd/jr-dev8
cd jr-dev8
jx remote secrets edit
jx remote run

jx remote secrets edit
Error: unknown command "remote" for "jx"

```
Lets remove the `remote` part and not sure we need `jx run`?  As I think this has been replaced with deploying the gitops operator?

**Comment by jstrachan** [comment]
fixed
