### ISSUE TITLE
ExternalSecrets service 

### ISSUE THREAD

**Issue by xcesiv** [jenkins-x/jx-admin#53]
Started from here:
https://github.com/jx3-gitops-repositories/jx3-eks-terraform-vault

Got to install Git Operator.
Installed git operator and nothing happens after I hit this:
```shell
# lets wait for the ExternalSecrets service to populate the mandatory Secret resources
VAULT_ADDR=https://vault.secret-infra:8200 jx secret wait
waiting for the mandatory Secrets to be populated from ExternalSecrets...
jenkins-x-chartmuseum: key secret/data/jx/adminUser missing properties: password, username
jx-pipeline-git-github-github: key secret/data/jx/pipelineUser missing properties: token, username
knative-docker-user-pass: key secret/data/knative/docker/user/pass missing properties: .dockerconfigjson
knative-git-user-pass: key secret/data/jx/pipelineUser missing properties: token, username
lighthouse-hmac-token: key secret/data/lighthouse/hmac missing properties: token
lighthouse-oauth-token: key secret/data/lighthouse/oauth missing properties: token
nexus: key secret/data/nexus missing properties: password
```
Just kinda sitting there. Not sure what to do next.

**Comment by jstrachan** [comment]
is this still an Issue? Lots of folks have had success with terraform, EKS and jx now.

if it is, do you have the external secrets pod running & vault up? Eg try `kubectl get pod -n secret-infra` and posting the output here

**Comment by xcesiv** [comment]
It is no longer an issue. Secrets pod was running but Vault wasn't up for some reason. Vault was failing to go up, so I tore down and restarted. Didn't run into issue again.
