### ISSUE TITLE
If remote upstream exists it is used instead of origin

### ISSUE THREAD

**Issue by yelhouti** [jenkins-x/jx-admin#86]
I added https://github.com/jx3-gitops-repositories/jx3-kubernetes as upstream in my repo to be able to compare my version with the upstream in case Kpt breaks something on jx gitops upgrade.
On the next jx admin operator, the operator confused it to be my url, create a secret for github instead of gitlab...
I think this is not expected behavior, am I wrong?

**Comment by jstrachan** [comment]
yeah - it should use origin before upstream to detect URLs
